[package]
name = "jsonwebtoken-botan"
version = "1.1.0"
license = "MIT"
readme = "readme.md"
description = "A Botan backed crypto provider for jsonwebtoken"
homepage = "https://github.com/arckoor/jsonwebtoken-providers/tree/main/jsonwebtoken-botan"
repository = "https://github.com/arckoor/jsonwebtoken-providers"
keywords = ["jwt"]
edition = "2024"

[dependencies]
jsonwebtoken = { workspace = true }
botan = { workspace = true }
