use std::{
    fs,
    str::FromStr,
    time::{SystemTime, UNIX_EPOCH},
};

use botan::{Privkey, RandomNumberGenerator};
use jsonwebtoken::{
    Algorithm, AlgorithmFamily, DecodingKey, EncodingKey, Header, Validation, decode, encode,
};
use openssl::{pkey::PKey, rand::rand_bytes, rsa::Rsa};
use provider_tests::{
    ALGORITHMS, Claims, Provider, install_from_provider, keypair_from_file, token_path,
};
use strum::IntoEnumIterator;

fn generate_keys_botan(algorithm: Algorithm) -> (EncodingKey, DecodingKey) {
    let mut rng = RandomNumberGenerator::new().unwrap();
    match algorithm.family() {
        AlgorithmFamily::Hmac => {
            let secret = rng.read(64).unwrap();
            (
                EncodingKey::from_secret(&secret),
                DecodingKey::from_secret(&secret),
            )
        }
        _ => {
            let algo = match algorithm.family() {
                AlgorithmFamily::Rsa => "RSA",
                AlgorithmFamily::Ec => "ECDSA",
                AlgorithmFamily::Ed => "Ed25519",
                _ => unreachable!(),
            };
            let params = match algorithm {
                Algorithm::ES256 => "secp256r1",
                Algorithm::ES384 => "secp384r1",
                _ => "",
            };
            let privkey = Privkey::create(algo, params, &mut rng).unwrap();

            let priv_pem = privkey.pem_encode().unwrap();
            let pub_pem = privkey.pubkey().unwrap().pem_encode().unwrap();

            match algorithm.family() {
                AlgorithmFamily::Rsa => (
                    EncodingKey::from_rsa_pem(priv_pem.as_bytes()).unwrap(),
                    DecodingKey::from_rsa_pem(pub_pem.as_bytes()).unwrap(),
                ),
                AlgorithmFamily::Ec => (
                    EncodingKey::from_ec_pem(priv_pem.as_bytes()).unwrap(),
                    DecodingKey::from_ec_pem(pub_pem.as_bytes()).unwrap(),
                ),
                AlgorithmFamily::Ed => (
                    EncodingKey::from_ed_pem(priv_pem.as_bytes()).unwrap(),
                    DecodingKey::from_ed_pem(pub_pem.as_bytes()).unwrap(),
                ),
                _ => unreachable!(),
            }
        }
    }
}

fn generate_keys_openssl(algorithm: Algorithm) -> (EncodingKey, DecodingKey) {
    match algorithm.family() {
        AlgorithmFamily::Hmac => {
            let mut secret = [0; 64];
            rand_bytes(&mut secret).unwrap();
            (
                EncodingKey::from_secret(&secret),
                DecodingKey::from_secret(&secret),
            )
        }
        _ => {
            let pkey = match algorithm.family() {
                AlgorithmFamily::Rsa => {
                    let key = Rsa::generate(4096).unwrap();
                    PKey::from_rsa(key).unwrap()
                }
                AlgorithmFamily::Ec => {
                    let curve = match algorithm {
                        Algorithm::ES256 => "P-256",
                        Algorithm::ES384 => "P-384",
                        _ => "",
                    };
                    PKey::ec_gen(curve).unwrap()
                }
                AlgorithmFamily::Ed => PKey::generate_ed25519().unwrap(),
                _ => unimplemented!(),
            };

            let priv_pem = pkey.private_key_to_pem_pkcs8().unwrap();
            let pub_pem = pkey.public_key_to_pem().unwrap();

            match algorithm.family() {
                AlgorithmFamily::Rsa => (
                    EncodingKey::from_rsa_pem(&priv_pem).unwrap(),
                    DecodingKey::from_rsa_pem(&pub_pem).unwrap(),
                ),
                AlgorithmFamily::Ec => (
                    EncodingKey::from_ec_pem(&priv_pem).unwrap(),
                    DecodingKey::from_ec_pem(&pub_pem).unwrap(),
                ),
                AlgorithmFamily::Ed => (
                    EncodingKey::from_ed_pem(&priv_pem).unwrap(),
                    DecodingKey::from_ed_pem(&pub_pem).unwrap(),
                ),
                _ => unreachable!(),
            }
        }
    }
}

fn sign_with_all_algorithms(
    provider: Provider,
    keygen_fn: fn(Algorithm) -> (EncodingKey, DecodingKey),
) {
    println!("Testing with keys generated by {provider}");
    for algorithm in ALGORITHMS {
        let algo = Algorithm::from_str(algorithm).unwrap();
        let (encoding_key, decoding_key) = keygen_fn(algo);

        println!("Testing {algo:?}");
        let exp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs()
            + 100;

        let claims = Claims {
            sub: "me".to_string(),
            exp,
        };

        let token = encode(&Header::new(algo), &claims, &encoding_key).unwrap();
        let decoded = decode::<Claims>(token, &decoding_key, &Validation::new(algo)).unwrap();

        assert_eq!(decoded.claims.sub, "me");
        assert_eq!(decoded.claims.exp, exp);
    }
}

fn verify_all_algorithms() {
    let hmac_key = keypair_from_file("hmac").1;
    let rsa_key = keypair_from_file("rsa").1;
    let ecdsa_key_256 = keypair_from_file("ecdsa_secp256r1").1;
    let ecdsa_key_384 = keypair_from_file("ecdsa_secp384r1").1;
    let eddsa_key = keypair_from_file("eddsa").1;

    for provider in Provider::iter() {
        for algorithm in ALGORITHMS {
            println!("Checking {}: {}", provider, algorithm);
            let algo = Algorithm::from_str(algorithm).unwrap();
            let token = fs::read_to_string(token_path(&provider, algorithm)).unwrap();
            let decoding_key = match algo {
                Algorithm::HS256 | Algorithm::HS384 | Algorithm::HS512 => &hmac_key,
                Algorithm::ES256 => &ecdsa_key_256,
                Algorithm::ES384 => &ecdsa_key_384,
                Algorithm::RS256
                | Algorithm::RS384
                | Algorithm::RS512
                | Algorithm::PS256
                | Algorithm::PS384
                | Algorithm::PS512 => &rsa_key,
                Algorithm::EdDSA => &eddsa_key,
                _ => {
                    println!("No test configured for algo {algo:?}");
                    continue;
                }
            };
            assert!(decode::<Claims>(token, decoding_key, &Validation::new(algo)).is_ok());
        }
    }
}

#[test]
fn sign_with_all_algorithms_botan() {
    install_from_provider(&Provider::Botan);

    sign_with_all_algorithms(Provider::Botan, generate_keys_botan);
    sign_with_all_algorithms(Provider::OpenSSL, generate_keys_openssl);
}

#[test]
fn sign_with_all_algorithms_openssl() {
    install_from_provider(&Provider::OpenSSL);

    sign_with_all_algorithms(Provider::Botan, generate_keys_botan);
    sign_with_all_algorithms(Provider::OpenSSL, generate_keys_openssl);
}

#[test]
fn verify_all_algorithms_aws_lc_rs() {
    install_from_provider(&Provider::AwsLcRs);

    verify_all_algorithms();
}

#[test]
fn verify_all_algorithms_rust_crypto() {
    install_from_provider(&Provider::RustCrypto);

    verify_all_algorithms();
}

#[test]
fn verify_all_algorithms_openssl() {
    install_from_provider(&Provider::OpenSSL);

    verify_all_algorithms();
}

#[test]
fn verify_all_algorithms_botan() {
    install_from_provider(&Provider::Botan);

    verify_all_algorithms();
}

#[test]
#[should_panic]
fn test_no_default_provider() {
    let exp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs()
        + 100;

    let claims = Claims {
        sub: "me".to_string(),
        exp,
    };

    let encoding_key = EncodingKey::from_secret(b"secret");

    let _ = encode(&Header::new(Algorithm::HS256), &claims, &encoding_key);
}
