use std::time::{SystemTime, UNIX_EPOCH};

use botan::{Privkey, RandomNumberGenerator};
use jsonwebtoken::{
    Algorithm, AlgorithmFamily, DecodingKey, EncodingKey, Header, Validation, decode, encode,
};
use openssl::{pkey::PKey, rand::rand_bytes, rsa::Rsa};
use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Eq, Clone, Serialize, Deserialize)]
pub struct Claims {
    sub: String,
    exp: u64,
}

fn generate_keys_botan(
    family: AlgorithmFamily,
    algorithm: Algorithm,
) -> (EncodingKey, DecodingKey) {
    let mut rng = RandomNumberGenerator::new().unwrap();
    match family {
        AlgorithmFamily::Hmac => {
            let secret = rng.read(64).unwrap();
            (
                EncodingKey::from_secret(&secret),
                DecodingKey::from_secret(&secret),
            )
        }
        _ => {
            let algo = match family {
                AlgorithmFamily::Rsa => "RSA",
                AlgorithmFamily::Ec => "ECDSA",
                AlgorithmFamily::Ed => "Ed25519",
                _ => unreachable!(),
            };
            let params = match algorithm {
                Algorithm::ES256 => "secp256r1",
                Algorithm::ES384 => "secp384r1",
                _ => "",
            };
            let privkey = Privkey::create(algo, params, &mut rng).unwrap();

            let priv_pem = privkey.pem_encode().unwrap();
            let pub_pem = privkey.pubkey().unwrap().pem_encode().unwrap();

            match family {
                AlgorithmFamily::Rsa => (
                    EncodingKey::from_rsa_pem(priv_pem.as_bytes()).unwrap(),
                    DecodingKey::from_rsa_pem(pub_pem.as_bytes()).unwrap(),
                ),
                AlgorithmFamily::Ec => (
                    EncodingKey::from_ec_pem(priv_pem.as_bytes()).unwrap(),
                    DecodingKey::from_ec_pem(pub_pem.as_bytes()).unwrap(),
                ),
                AlgorithmFamily::Ed => (
                    EncodingKey::from_ed_pem(priv_pem.as_bytes()).unwrap(),
                    DecodingKey::from_ed_pem(pub_pem.as_bytes()).unwrap(),
                ),
                _ => unreachable!(),
            }
        }
    }
}

fn generate_keys_openssl(
    family: AlgorithmFamily,
    algorithm: Algorithm,
) -> (EncodingKey, DecodingKey) {
    match family {
        AlgorithmFamily::Hmac => {
            let mut secret = [0; 64];
            rand_bytes(&mut secret).unwrap();
            (
                EncodingKey::from_secret(&secret),
                DecodingKey::from_secret(&secret),
            )
        }
        _ => {
            let pkey = match family {
                AlgorithmFamily::Rsa => {
                    let key = Rsa::generate(4096).unwrap();
                    PKey::from_rsa(key).unwrap()
                }
                AlgorithmFamily::Ec => {
                    let curve = match algorithm {
                        Algorithm::ES256 => "P-256",
                        Algorithm::ES384 => "P-384",
                        _ => "",
                    };
                    PKey::ec_gen(curve).unwrap()
                }
                AlgorithmFamily::Ed => PKey::generate_ed25519().unwrap(),
                _ => unimplemented!(),
            };

            let priv_pem = pkey.private_key_to_pem_pkcs8().unwrap();
            let pub_pem = pkey.public_key_to_pem().unwrap();

            match family {
                AlgorithmFamily::Rsa => (
                    EncodingKey::from_rsa_pem(&priv_pem).unwrap(),
                    DecodingKey::from_rsa_pem(&pub_pem).unwrap(),
                ),
                AlgorithmFamily::Ec => (
                    EncodingKey::from_ec_pem(&priv_pem).unwrap(),
                    DecodingKey::from_ec_pem(&pub_pem).unwrap(),
                ),
                AlgorithmFamily::Ed => (
                    EncodingKey::from_ed_pem(&priv_pem).unwrap(),
                    DecodingKey::from_ed_pem(&pub_pem).unwrap(),
                ),
                _ => unreachable!(),
            }
        }
    }
}

fn test_all_algorithms(
    keygen: &str,
    keygen_fn: fn(AlgorithmFamily, Algorithm) -> (EncodingKey, DecodingKey),
) {
    println!("Testing with keys generated by {keygen}");
    let algos = [
        (AlgorithmFamily::Hmac, Algorithm::HS256),
        (AlgorithmFamily::Hmac, Algorithm::HS384),
        (AlgorithmFamily::Hmac, Algorithm::HS512),
        (AlgorithmFamily::Rsa, Algorithm::RS256),
        (AlgorithmFamily::Rsa, Algorithm::RS384),
        (AlgorithmFamily::Rsa, Algorithm::RS512),
        (AlgorithmFamily::Rsa, Algorithm::PS256),
        (AlgorithmFamily::Rsa, Algorithm::PS384),
        (AlgorithmFamily::Rsa, Algorithm::PS512),
        (AlgorithmFamily::Ec, Algorithm::ES256),
        (AlgorithmFamily::Ec, Algorithm::ES384),
        (AlgorithmFamily::Ed, Algorithm::EdDSA),
    ];

    for (family, algo) in algos {
        let (encoding_key, decoding_key) = keygen_fn(family, algo);

        println!("Testing {algo:?}");
        let exp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs()
            + 100;

        let claims = Claims {
            sub: "me".to_string(),
            exp,
        };

        let token = encode(&Header::new(algo), &claims, &encoding_key).unwrap();
        let decoded = decode::<Claims>(token, &decoding_key, &Validation::new(algo)).unwrap();

        assert_eq!(decoded.claims.sub, "me");
        assert_eq!(decoded.claims.exp, exp);
    }
}

#[test]
fn test_all_algorithms_botan() {
    jsonwebtoken_botan::install_default().unwrap();

    test_all_algorithms("botan", generate_keys_botan);
    test_all_algorithms("openssl", generate_keys_openssl);
}

#[test]
fn test_all_algorithms_openssl() {
    jsonwebtoken_openssl::install_default().unwrap();

    test_all_algorithms("botan", generate_keys_botan);
    test_all_algorithms("openssl", generate_keys_openssl);
}

#[test]
#[should_panic]
fn test_no_default_provider() {
    let exp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs()
        + 100;

    let claims = Claims {
        sub: "me".to_string(),
        exp,
    };

    let encoding_key = EncodingKey::from_secret(b"secret");

    let _ = encode(&Header::new(Algorithm::HS256), &claims, &encoding_key);
}
